import "../styles/landingPage.css";
import {
  FaRobot,
  FaChartLine,
  FaCode,
  FaArrowRight,
  FaGithub,
  FaLinkedin,
  FaTwitter,
  FaInstagram,
  FaChevronDown,
} from "react-icons/fa";

import { useState } from "react";
import { useNavigate } from "react-router-dom";

function LandingPage() {
    const faqs = [
  {
    question: "How does the AI generate interview questions?",
    answer:
      "Questions are generated dynamically based on your selected role, experience level, and difficulty using Google Gemini AI.",
  },
  {
    question: "Can I practice unlimited interviews?",
    answer:
      "Yes. You can create and practice as many interviews as you want.",
  },
  {
    question: "Does the platform support voice answers?",
    answer:
      "Yes. We use the browser's Speech Recognition API to convert your speech into text.",
  },
  {
    question: "Will I receive detailed feedback?",
    answer:
      "Absolutely! Every answer is scored with strengths, weaknesses and improvement suggestions.",
  },
];

const [openFAQ, setOpenFAQ] = useState(null);

const hadleGithub=  () => {
    window.open("https://github.com/sakshamg1152", "_blank"); 
}
const hadleLinkedin = () =>{
    window.open("https://www.linkedin.com/in/saksham-gupta-5299053a2/", "_blank");
}
const router = useNavigate();

const handleFeatures = () => {
    document.querySelector(".featuresSection").scrollIntoView({
        behavior: "smooth"
    });
};
const handleFAQ = () => {
    document.querySelector(".faqSection").scrollIntoView({
        behavior: "smooth"
    });
};
const handleTestimonals = () => {
    document.querySelector(".testimonialSection").scrollIntoView({
        behavior: "smooth"
    });
};
const handleRole = () => {
    document.querySelector(".rolesSection").scrollIntoView({
        behavior: "smooth"
    });
};
  return (
    <div className="landing">

      {/* Navbar */}

      <nav className="navbar">

        <div className="logo">

          <FaRobot className="logoIcon"/>

          <h2>MockAI</h2>

        </div>

        <ul className="navLinks">
          <li onClick={handleFeatures}>Features</li>
          <li onClick={handleRole}>Roles</li>
          <li onClick={handleTestimonals}>Testimonials</li>
          <li onClick={handleFAQ}>FAQ</li>
        </ul>

        <div className="navButtons">
          <button className="loginBtn" onClick={()=> router("/auth")}>Login</button>

          <button className="startBtn" onClick={()=> router("/auth")}>
            Get Started
          </button>
        </div>

      </nav>


      {/* Hero */}

      <section className="hero">

        {/* Left */}

        <div className="heroLeft">

          <span className="badge">
            AI Powered Mock Interviews
          </span>

          <h1>

            Ace Your <span>Next</span>

            <br />

            Interview With AI

          </h1>

          <p>

            Practice real interview questions generated by AI.

            Receive detailed feedback, score reports and improve
            your chances of cracking top tech companies.

          </p>

          <div className="heroButtons">

            <button className="primaryBtn" onClick={() => router("/auth")}>

              Get Started

              <FaArrowRight />

            </button>


          </div>

          <div className="heroUsers">

            <div className="avatars">

              <div></div>
              <div></div>
              <div></div>
              <div></div>

            </div>

            <span>

              Trusted by <strong>10,000+</strong> Students

            </span>

          </div>

        </div>

        {/* Right */}

        <div className="heroRight">

            <div className="heroImageContainer">

                <img
                    src="/images/hero-ai.png"
                    alt="AI Mock Interview"
                    className="heroImage"
                />

            </div>

        </div>

      </section>
      {/* ================= ROLES SECTION ================= */}

<section className="rolesSection">

    <div className="sectionHeading">

        <span className="miniTitle">
            Choose Your Career Path
        </span>

        <h2>

            Practice Interviews For

            <span> Every Role</span>

        </h2>

        <p>

            AI generates company-level interview questions
            based on your selected role and experience.

        </p>

    </div>


    <div className="rolesGrid">

        <div className="roleCard">

            <div className="emoji">💻</div>

            <h3>Frontend Developer</h3>

            <p>React • HTML • CSS • JavaScript</p>

            <span>25+ Interview Questions</span>

        </div>

        <div className="roleCard">

            <div className="emoji">⚙️</div>

            <h3>Backend Developer</h3>

            <p>Node • Express • MongoDB</p>

            <span>30+ Interview Questions</span>

        </div>

        <div className="roleCard">

            <div className="emoji">🚀</div>

            <h3>Full Stack Developer</h3>

            <p>MERN Stack • APIs • JWT</p>

            <span>40+ Interview Questions</span>

        </div>

        <div className="roleCard">

            <div className="emoji">📊</div>

            <h3>Data Analyst</h3>

            <p>SQL • Python • Excel</p>

            <span>20+ Interview Questions</span>

        </div>

        <div className="roleCard">

            <div className="emoji">👨‍💼</div>

            <h3>HR Interview</h3>

            <p>Communication • Behavioural</p>

            <span>15+ Interview Questions</span>

        </div>

        <div className="roleCard">

            <div className="emoji">🏗️</div>

            <h3>System Design</h3>

            <p>LLD • HLD • Scalability</p>

            <span>35+ Interview Questions</span>

        </div>

    </div>

</section>
{/* ================= FEATURES SECTION ================= */}

<section className="featuresSection">

    <div className="sectionHeading">

        <span className="miniTitle">
            Powerful Features
        </span>

        <h2>

            Everything You Need To

            <span> Crack Interviews</span>

        </h2>

        <p>

            Practice smarter with AI-generated interviews,
            instant evaluation, detailed reports and progress
            tracking—all in one platform.

        </p>

    </div>

    <div className="featureGrid">

        <div className="featureCard large">

            <div className="featureIcon">🤖</div>

            <h3>AI Interview Generator</h3>

            <p>

                Generate realistic interview questions
                based on role, experience and difficulty.
                Every interview is unique.

            </p>

        </div>

        <div className="featureCard">

            <div className="featureIcon">🎤</div>

            <h3>Voice Answers</h3>

            <p>

                Speak naturally and convert your speech
                into text using browser speech recognition.

            </p>

        </div>

        <div className="featureCard">

            <div className="featureIcon">📊</div>

            <h3>Detailed Reports</h3>

            <p>

                Receive AI scores, strengths,
                weaknesses and improvement tips.

            </p>

        </div>

        <div className="featureCard">

            <div className="featureIcon">📈</div>

            <h3>Progress Tracking</h3>

            <p>

                Monitor your interview performance
                through beautiful analytics.

            </p>

        </div>

        <div className="featureCard">

            <div className="featureIcon">📚</div>

            <h3>Interview History</h3>

            <p>

                Access every previous interview,
                answers and reports anytime.

            </p>

        </div>

        <div className="featureCard large">

            <div className="featureIcon">🔐</div>

            <h3>Secure Authentication</h3>

            <p>

                JWT authentication, encrypted passwords,
                protected routes and secure user sessions.

            </p>

        </div>

    </div>

</section>
{/* ===================== STATS SECTION ===================== */}

<section className="statsSection">

  <div className="sectionHeading">
    <span className="miniTitle">Our Impact</span>

    <h2>
      Trusted By <span>Thousands Of Students</span>
    </h2>

    <p>
      Join developers, freshers and professionals who prepare for interviews
      using MockAI every day.
    </p>
  </div>

  <div className="statsGrid">

    <div className="statCard">
      <h2>10K+</h2>
      <p>Interviews Completed</p>
    </div>

    <div className="statCard">
      <h2>95%</h2>
      <p>User Satisfaction</p>
    </div>

    <div className="statCard">
      <h2>50+</h2>
      <p>Interview Categories</p>
    </div>

    <div className="statCard">
      <h2>24/7</h2>
      <p>AI Availability</p>
    </div>

  </div>

</section>


{/* ===================== COMPANIES ===================== */}

<section className="companiesSection">

    <h3>Inspired by interview processes at</h3>

    <div className="companies">

        <div>Google</div>
        <div>Microsoft</div>
        <div>Amazon</div>
        <div>Meta</div>
        <div>Adobe</div>
        <div>Netflix</div>

    </div>

</section>



{/* ===================== TESTIMONIALS ===================== */}

<section className="testimonialSection">

    <div className="sectionHeading">

        <span className="miniTitle">
            Testimonials
        </span>

        <h2>

            Loved By

            <span> Students</span>

        </h2>

    </div>

    <div className="testimonialGrid">

        <div className="testimonial">

            <div className="profile">

                <div className="avatar">S</div>

                <div>

                    <h4>Saksham Gupta</h4>

                    <span>Frontend Developer</span>

                </div>

            </div>

            <p>

                The AI feedback helped me understand
                where I was making mistakes.
                I cracked my internship interview after
                practicing for a week.

            </p>

            <div className="stars">
                ⭐⭐⭐⭐⭐
            </div>

        </div>


        <div className="testimonial">

            <div className="profile">

                <div className="avatar">R</div>

                <div>

                    <h4>Nupur Gupta</h4>

                    <span>Backend Developer</span>

                </div>

            </div>

            <p>

                Better than watching interview videos.
                The AI asks different questions every
                time which makes practice realistic.

            </p>

            <div className="stars">
                ⭐⭐⭐⭐⭐
            </div>

        </div>

        <div className="testimonial">

            <div className="profile">

                <div className="avatar">A</div>

                <div>

                    <h4>Eshika Agrarwaal</h4>

                    <span>Software Engineer</span>

                </div>

            </div>

            <p>

                The detailed report after every interview
                is my favorite feature.
                Highly recommended.

            </p>

            <div className="stars">
                ⭐⭐⭐⭐⭐
            </div>

        </div>

    </div>

</section>



{/* ===================== CTA ===================== */}

<section className="ctaSection">

    <div className="ctaCard">

        <h2>

            Ready To Ace Your Next Interview?

        </h2>

        <p>

            Practice unlimited AI interviews and
            receive instant personalized feedback.

        </p>

        <button onClick={() => router("/auth")}>

            Start Free Interview

        </button>

    </div>

</section>
{/* ================= FAQ ================= */}

<section className="faqSection">

    <div className="sectionHeading">

        <span className="miniTitle">
            Frequently Asked Questions
        </span>

        <h2>

            Got Questions?

            <span> We've Got Answers</span>

        </h2>

    </div>

    <div className="faqContainer">

        {faqs.map((faq, index) => (

            <div
                className="faqItem"
                key={index}
                onClick={() =>
                    setOpenFAQ(openFAQ === index ? null : index)
                }
            >

                <div className="faqQuestion">

                    <h3>{faq.question}</h3>

                    <FaChevronDown
                        className={
                            openFAQ === index ? "rotateIcon" : ""
                        }
                    />

                </div>

                {openFAQ === index && (

                    <div className="faqAnswer">

                        {faq.answer}

                    </div>

                )}

            </div>

        ))}

    </div>

</section>



{/* ================= FOOTER ================= */}

<footer className="footer">

    <div className="footerTop">

        <div className="footerLogo">

            <FaRobot className="footerRobot"/>

            <h2>MockAI</h2>

            <p>

                AI Powered Interview Practice Platform
                helping students and professionals
                crack their dream jobs.

            </p>

            <div className="socialIcons">

                <FaGithub onClick={hadleGithub}/>

                <FaLinkedin onClick={hadleLinkedin}/>

            </div>

        </div>

        <div>

            <h3>Product</h3>

            <ul>

                <li>Dashboard</li>
                <li>Create Interview</li>
                <li>Reports</li>
                <li>History</li>

            </ul>

        </div>

        <div>

            <h3>Resources</h3>

            <ul>

                <li>Documentation</li>
                <li>Blog</li>
                <li>FAQs</li>
                <li>Support</li>

            </ul>

        </div>

        <div>

            <h3>Newsletter</h3>

            <p>

                Stay updated with new AI interview
                features.

            </p>


        </div>

    </div>

    <hr/>

    <div className="footerBottom">

        © 2026 MockAI • Built with React & AI

    </div>

</footer>

    </div>
  );
}


export default LandingPage;